var floatAge, floatDays, floatWeeks,floatMonths, floatFortnights;
floatAge = parseFloat(prompt("What is your current age in years?"));
floatDays = floatAge * 365.25;
floatMonths = floatAge * 12;
floatWeeks = floatDays / 7;
floatFortnights =floatDays /14;
alert("You are " + floatAge + " years old.");
alert("You are " + floatDays + " days old.");
alert("You are " + floatWeeks + " weeks old.");
alert("You are " + floatMonths + " months old.");
alert("You are " + floatFortnights + " fortnights old/");
